dist: bionic
language: cpp
os: linux

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'gcc-9', 'g++-9' ]
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

    - os: linux
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'clang-9' ]
      env:
        - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - pip install --user conan cmake
  - conan profile new default --detect
  - conan profile update settings.compiler.libcxx=libstdc++11 default

script:
  - cmake -DCMAKE_BUILD_TYPE=Debug .
  - cmake --build . -- VERBOSE=1 -j2
  - cd ./tests && ctest -j2
